/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Warehouse;

import java.awt.Color;

/**
 *
 * @author Yeabsra Debebe
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Pane = new javax.swing.JPanel();
        Side_Pane = new javax.swing.JPanel();
        More_Option = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Home_Option = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Sign_In_Option = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Contacts = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Main_Pane = new javax.swing.JPanel();
        Home_Pane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Title_Pane1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Pane.setBackground(new java.awt.Color(6, 13, 16));
        Title_Pane.setForeground(new java.awt.Color(51, 51, 51));
        Title_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Side_Pane.setBackground(new java.awt.Color(22, 30, 34));
        Side_Pane.setForeground(new java.awt.Color(51, 51, 51));
        Side_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        More_Option.setBackground(new java.awt.Color(22, 30, 34));
        More_Option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                More_OptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                More_OptionMouseExited(evt);
            }
        });
        More_Option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_More_24px.png"))); // NOI18N
        More_Option.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        Side_Pane.add(More_Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 60, 40));

        Home_Option.setBackground(new java.awt.Color(51, 51, 51));
        Home_Option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Home_24px.png"))); // NOI18N
        Home_Option.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        Side_Pane.add(Home_Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 40));

        Sign_In_Option.setBackground(new java.awt.Color(22, 30, 34));
        Sign_In_Option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sign_In_OptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Sign_In_OptionMouseExited(evt);
            }
        });
        Sign_In_Option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_User_24px.png"))); // NOI18N
        Sign_In_Option.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        Side_Pane.add(Sign_In_Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 40));

        Contacts.setBackground(new java.awt.Color(22, 30, 34));
        Contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactsMouseExited(evt);
            }
        });
        Contacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Contacts_24px.png"))); // NOI18N
        Contacts.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 20));

        Side_Pane.add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 60, 40));

        Settings.setBackground(new java.awt.Color(22, 30, 34));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
        });
        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Settings_24px.png"))); // NOI18N
        Settings.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        Side_Pane.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 60, 40));

        Title_Pane.add(Side_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        Main_Pane.setBackground(new java.awt.Color(9, 22, 30));
        Main_Pane.setForeground(new java.awt.Color(51, 51, 51));
        Main_Pane.setLayout(new java.awt.CardLayout());

        Home_Pane.setBackground(new java.awt.Color(9, 22, 30));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Home");

        javax.swing.GroupLayout Home_PaneLayout = new javax.swing.GroupLayout(Home_Pane);
        Home_Pane.setLayout(Home_PaneLayout);
        Home_PaneLayout.setHorizontalGroup(
            Home_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(601, Short.MAX_VALUE))
        );
        Home_PaneLayout.setVerticalGroup(
            Home_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        Main_Pane.add(Home_Pane, "card2");

        Title_Pane.add(Main_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 710, 430));

        getContentPane().add(Title_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 770, 430));

        Title_Pane1.setBackground(new java.awt.Color(4, 7, 12));
        Title_Pane1.setForeground(new java.awt.Color(51, 51, 51));
        Title_Pane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Title_Pane1MouseDragged(evt);
            }
        });
        Title_Pane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Title_Pane1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Title_Pane1MouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Rectangle_18px_4.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Rectangle_18px_3.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_Store/icons8_Rectangle_18px_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Title_Pane1Layout = new javax.swing.GroupLayout(Title_Pane1);
        Title_Pane1.setLayout(Title_Pane1Layout);
        Title_Pane1Layout.setHorizontalGroup(
            Title_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title_Pane1Layout.createSequentialGroup()
                .addContainerGap(702, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2))
        );
        Title_Pane1Layout.setVerticalGroup(
            Title_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_Pane1Layout.createSequentialGroup()
                .addGroup(Title_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Title_Pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 20));

        setSize(new java.awt.Dimension(769, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx, yy;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Title_Pane1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_Pane1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xx, y - yy);
        this.setOpacity((float)0.8);
    }//GEN-LAST:event_Title_Pane1MouseDragged

    private void Title_Pane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_Pane1MousePressed
        xx = evt.getX(); 
        yy = evt.getY();
    }//GEN-LAST:event_Title_Pane1MousePressed

    private void Title_Pane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_Pane1MouseReleased
        this.setOpacity((float)1);
    }//GEN-LAST:event_Title_Pane1MouseReleased

    private void Sign_In_OptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_In_OptionMouseEntered
        Color clr = Home_Option.getBackground();
        Sign_In_Option.setBackground(clr);
    }//GEN-LAST:event_Sign_In_OptionMouseEntered

    private void Sign_In_OptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_In_OptionMouseExited
        Color clr = Contacts.getBackground();
        Sign_In_Option.setBackground(clr);
    }//GEN-LAST:event_Sign_In_OptionMouseExited

    private void ContactsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactsMouseEntered
        Color clr = Home_Option.getBackground();
        Contacts.setBackground(clr);
    }//GEN-LAST:event_ContactsMouseEntered

    private void ContactsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactsMouseExited
        Color clr = Sign_In_Option.getBackground();
        Contacts.setBackground(clr);
    }//GEN-LAST:event_ContactsMouseExited

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        Color clr = Sign_In_Option.getBackground();
        Settings.setBackground(clr);
    }//GEN-LAST:event_SettingsMouseExited

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        Color clr = Home_Option.getBackground();
        Settings.setBackground(clr);
    }//GEN-LAST:event_SettingsMouseEntered

    private void More_OptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More_OptionMouseEntered
        Color clr = Home_Option.getBackground();
        More_Option.setBackground(clr);
    }//GEN-LAST:event_More_OptionMouseEntered

    private void More_OptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More_OptionMouseExited
        Color clr = Sign_In_Option.getBackground();
        More_Option.setBackground(clr);
    }//GEN-LAST:event_More_OptionMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Contacts;
    public javax.swing.JPanel Home_Option;
    private javax.swing.JPanel Home_Pane;
    private javax.swing.JPanel Main_Pane;
    public javax.swing.JPanel More_Option;
    public javax.swing.JPanel Settings;
    private javax.swing.JPanel Side_Pane;
    public javax.swing.JPanel Sign_In_Option;
    private javax.swing.JPanel Title_Pane;
    private javax.swing.JPanel Title_Pane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
