/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleCalculator;

/**
 *
 * @author Yeabsra Debebe
 */
public class Home_Interface extends javax.swing.JFrame {
    
    String operType;                // Represents the type of operation       
    double first_num, second_num;   // Hold the numbers entered by the user
    boolean clicked, finished_calc; // Checks if the dot is clicked, and also 
                                    // checks if calculation is finished
    double sum, prod, div, sub;     // values representing each operation type
    
    /**
     * Creates new form Home_Interface
     */
    public Home_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        List_Menu = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        one = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        three = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        two = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        plus = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        minus = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        four = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        five = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        multiply = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        divide = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        seven = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        six = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        nine = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        eight = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        equals_to = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        plus_minus = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        zero = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        clear = new javax.swing.JLabel();
        dotPanel = new javax.swing.JPanel();
        point = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        approx_to = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        Pri_Disp = new javax.swing.JTextField();
        Sec_Disp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Minus_20px.png")); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 20));

        List_Menu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Menu_20px.png")); // NOI18N
        jPanel1.add(List_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Cancel_20px.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        one.setBackground(new java.awt.Color(204, 204, 255));
        one.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        one.setForeground(new java.awt.Color(204, 204, 255));
        one.setText("  1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });
        jPanel3.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        three.setBackground(new java.awt.Color(204, 204, 255));
        three.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        three.setForeground(new java.awt.Color(204, 204, 255));
        three.setText("  3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });
        jPanel4.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        two.setBackground(new java.awt.Color(204, 204, 255));
        two.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        two.setForeground(new java.awt.Color(204, 204, 255));
        two.setText("  2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        jPanel5.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plus.setBackground(new java.awt.Color(204, 204, 255));
        plus.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        plus.setForeground(new java.awt.Color(204, 204, 255));
        plus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Plus_Math_40px.png")); // NOI18N
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
        });
        jPanel6.add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minus.setBackground(new java.awt.Color(204, 204, 255));
        minus.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        minus.setForeground(new java.awt.Color(204, 204, 255));
        minus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Subtract_40px.png")); // NOI18N
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
        });
        jPanel7.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        four.setBackground(new java.awt.Color(204, 204, 255));
        four.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        four.setForeground(new java.awt.Color(204, 204, 255));
        four.setText("  4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });
        jPanel8.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        five.setBackground(new java.awt.Color(204, 204, 255));
        five.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        five.setForeground(new java.awt.Color(204, 204, 255));
        five.setText("  5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });
        jPanel9.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        multiply.setBackground(new java.awt.Color(204, 204, 255));
        multiply.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        multiply.setForeground(new java.awt.Color(204, 204, 255));
        multiply.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Multiply_40px.png")); // NOI18N
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyMouseClicked(evt);
            }
        });
        jPanel12.add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        divide.setBackground(new java.awt.Color(204, 204, 255));
        divide.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        divide.setForeground(new java.awt.Color(204, 204, 255));
        divide.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Divide_40px.png")); // NOI18N
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });
        jPanel13.add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seven.setBackground(new java.awt.Color(204, 204, 255));
        seven.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        seven.setForeground(new java.awt.Color(204, 204, 255));
        seven.setText("  7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });
        jPanel14.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        six.setBackground(new java.awt.Color(204, 204, 255));
        six.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        six.setForeground(new java.awt.Color(204, 204, 255));
        six.setText("  6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });
        jPanel15.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nine.setBackground(new java.awt.Color(204, 204, 255));
        nine.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        nine.setForeground(new java.awt.Color(204, 204, 255));
        nine.setText("  9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });
        jPanel16.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel18.setBackground(new java.awt.Color(0, 153, 153));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eight.setBackground(new java.awt.Color(204, 204, 255));
        eight.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        eight.setForeground(new java.awt.Color(204, 204, 255));
        eight.setText("  8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        jPanel18.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel20.setBackground(new java.awt.Color(0, 153, 153));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equals_to.setBackground(new java.awt.Color(204, 204, 255));
        equals_to.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        equals_to.setForeground(new java.awt.Color(204, 204, 255));
        equals_to.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Equal_Sign_40px.png")); // NOI18N
        equals_to.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equals_toMouseClicked(evt);
            }
        });
        jPanel20.add(equals_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel21.setBackground(new java.awt.Color(0, 153, 153));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plus_minus.setBackground(new java.awt.Color(204, 204, 255));
        plus_minus.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        plus_minus.setForeground(new java.awt.Color(204, 204, 255));
        plus_minus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Plus_Minus_40px.png")); // NOI18N
        plus_minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus_minusMouseClicked(evt);
            }
        });
        jPanel21.add(plus_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel23.setBackground(new java.awt.Color(0, 153, 153));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zero.setBackground(new java.awt.Color(204, 204, 255));
        zero.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        zero.setForeground(new java.awt.Color(204, 204, 255));
        zero.setText("  0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });
        jPanel23.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel24.setBackground(new java.awt.Color(0, 153, 153));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clear.setBackground(new java.awt.Color(204, 204, 255));
        clear.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        clear.setForeground(new java.awt.Color(204, 204, 255));
        clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Clear_Symbol_40px.png")); // NOI18N
        jPanel24.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        dotPanel.setBackground(new java.awt.Color(0, 153, 153));
        dotPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotPanelMouseClicked(evt);
            }
        });
        dotPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        point.setBackground(new java.awt.Color(204, 204, 255));
        point.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        point.setForeground(new java.awt.Color(204, 204, 255));
        point.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimpleCalculator/icons8_New_Moon_10px.png"))); // NOI18N
        dotPanel.add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 20, 20));

        jPanel27.setBackground(new java.awt.Color(0, 153, 153));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approx_to.setBackground(new java.awt.Color(204, 204, 255));
        approx_to.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        approx_to.setForeground(new java.awt.Color(204, 204, 255));
        approx_to.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yeabsra Debebe\\Documents\\NetBeansProjects\\MetroCalc\\src\\SimpleCalculator\\icons8_Approximately_Equal_40px.png")); // NOI18N
        jPanel27.add(approx_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jPanel28.setBackground(new java.awt.Color(0, 153, 153));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(204, 204, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 255));
        jLabel24.setText("CE");
        jPanel28.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel26.setBackground(new java.awt.Color(0, 153, 153));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBackground(new java.awt.Color(204, 204, 255));
        cancel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        cancel.setForeground(new java.awt.Color(204, 204, 255));
        cancel.setText(" C");
        jPanel26.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 350));

        Pri_Disp.setEditable(false);
        Pri_Disp.setBackground(new java.awt.Color(0, 102, 102));
        Pri_Disp.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Pri_Disp.setForeground(new java.awt.Color(204, 204, 255));
        Pri_Disp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Pri_Disp.setText("0");
        Pri_Disp.setBorder(null);
        Pri_Disp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Pri_Disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_DispActionPerformed(evt);
            }
        });
        getContentPane().add(Pri_Disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 40));

        Sec_Disp.setEditable(false);
        Sec_Disp.setBackground(new java.awt.Color(0, 102, 102));
        Sec_Disp.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        Sec_Disp.setForeground(new java.awt.Color(204, 204, 255));
        Sec_Disp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Sec_Disp.setText("0");
        Sec_Disp.setBorder(null);
        Sec_Disp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Sec_Disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sec_DispActionPerformed(evt);
            }
        });
        getContentPane().add(Sec_Disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 90));

        setSize(new java.awt.Dimension(298, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked

    }//GEN-LAST:event_minMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("1"); 
        }
        else
             Sec_Disp.setText(Sec_Disp.getText() + "1"); 
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("1"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "1");
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("2"); 
        }
        else
             Sec_Disp.setText(Sec_Disp.getText() + "2"); 
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("2"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "2");
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("3"); 
        }
        else
             Sec_Disp.setText(Sec_Disp.getText() + "3");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("3"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "3");
    }//GEN-LAST:event_threeMouseClicked

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
        operType = "Add";
        if (finished_calc == true) {
            first_num = second_num;
            Pri_Disp.setText("ANS + ");
        }
        else {
        first_num = Double.parseDouble(Sec_Disp.getText());
        Sec_Disp.setText("0");
        Pri_Disp.setText(Pri_Disp.getText() + " + ");
        }
    }//GEN-LAST:event_plusMouseClicked

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked
        operType = "Sub";
        if (finished_calc == true) {
            first_num = second_num;
            Pri_Disp.setText("ANS - ");
        }
        else {
        first_num = Double.parseDouble(Sec_Disp.getText());
        Sec_Disp.setText("0");
        Pri_Disp.setText(Pri_Disp.getText() + " - ");
        }
    }//GEN-LAST:event_minusMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("4"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "4");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("4"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "4");
    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("5"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "5");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("5"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "5");
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("6"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "6");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("6"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "6");
    }//GEN-LAST:event_sixMouseClicked

    private void multiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseClicked
       operType = "Mul";
       first_num = Double.parseDouble(Sec_Disp.getText());
       Sec_Disp.setText("0");
       Pri_Disp.setText(Pri_Disp.getText() + " x ");
    }//GEN-LAST:event_multiplyMouseClicked

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
       operType = "Div";
       first_num = Double.parseDouble(Sec_Disp.getText());
       Sec_Disp.setText("0");
       Pri_Disp.setText(Pri_Disp.getText() + " / " );
    }//GEN-LAST:event_divideMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("8"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "8"); 
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("8"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "8");
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("9"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "9");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("9"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "9");
    }//GEN-LAST:event_nineMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("0"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "0");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("0"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "0");
    }//GEN-LAST:event_zeroMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        if (finished_calc == true) {
            Pri_Disp.setText("0");
            Sec_Disp.setText("0");
        }
        
        if ("0".equals(Sec_Disp.getText())) 
        {
            Sec_Disp.setText("7"); 
        }
        else
            Sec_Disp.setText(Sec_Disp.getText() + "7");
        
        if ("0".equals(Pri_Disp.getText())) 
        {
            Pri_Disp.setText("7"); 
        }
        else
            Pri_Disp.setText(Pri_Disp.getText() + "7");
    }//GEN-LAST:event_sevenMouseClicked

    private void Sec_DispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sec_DispActionPerformed

    }//GEN-LAST:event_Sec_DispActionPerformed

    private void Pri_DispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_DispActionPerformed
    
    }//GEN-LAST:event_Pri_DispActionPerformed

    private void dotPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotPanelMouseClicked
        if (clicked == false) {
        Pri_Disp.setText(Pri_Disp.getText() + ".");
        Sec_Disp.setText(Sec_Disp.getText() + ".");
        }
        clicked = true;     
    }//GEN-LAST:event_dotPanelMouseClicked

    private void equals_toMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equals_toMouseClicked
        second_num = Double.parseDouble(Sec_Disp.getText());
        if (finished_calc != true) {
            switch (operType) {
                case "Add":
                    sum = first_num + second_num;
                    Sec_Disp.setText( sum + "");
                    Pri_Disp.setText(Pri_Disp.getText() + " = " + sum);
                    break;
                case "Sub":
                    sub = first_num - second_num;
                    Sec_Disp.setText( sub + "");
                    Pri_Disp.setText(Pri_Disp.getText() + " = " + sub);
                    break;
                case "Mul":
                    prod = first_num * second_num;
                    Sec_Disp.setText( prod + "");
                    Pri_Disp.setText(Pri_Disp.getText() + " = " + prod);
                    break;
                case "Div":
                    div = first_num / second_num;
                    Sec_Disp.setText( div + "");
                    Pri_Disp.setText(Pri_Disp.getText() + " = " + div);
                    break;
                default:
                    break;
            }
        }
        else
        finished_calc = true;
    }//GEN-LAST:event_equals_toMouseClicked

    private void plus_minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_minusMouseClicked
        if (Sec_Disp.getText().charAt(0) == '-') {
            String str = "";
            for(int i = 0; i <= Sec_Disp.getText().length(); i++) {
                if (Sec_Disp.getText().charAt(i) != '-')
                   str = str + Sec_Disp.getText().charAt(i); 
            }
            Sec_Disp.setText(str);
            Pri_Disp.setText(str);
        }
        else {
            Sec_Disp.setText("-" + Sec_Disp.getText());
            Pri_Disp.setText("-" + Pri_Disp.getText());
        }
            
        
    }//GEN-LAST:event_plus_minusMouseClicked
    int xx, yy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home_Interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel List_Menu;
    private javax.swing.JTextField Pri_Disp;
    private javax.swing.JTextField Sec_Disp;
    private javax.swing.JLabel approx_to;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel close;
    private javax.swing.JLabel divide;
    private javax.swing.JPanel dotPanel;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel equals_to;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel min;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel multiply;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel one;
    private javax.swing.JLabel plus;
    private javax.swing.JLabel plus_minus;
    private javax.swing.JLabel point;
    private javax.swing.JLabel seven;
    private javax.swing.JLabel six;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables
}
